-- Development auth bypass applied with:
-- npx @insforge/cli db query --unrestricted
--
-- The normal migration runner is intentionally not allowed to update
-- InsForge-managed auth.config/auth.users rows. The project backend was
-- updated to:
-- - set auth.config.require_email_verification = false
-- - mark existing auth.users.email_verified = true
-- - create auth.dev_auto_verify_user_email()
-- - attach dev_auto_verify_user_email before insert on auth.users
select 1;
